-- Drop CLOTHING_DETAILS table as it's not used
DROP TABLE IF EXISTS CLOTHING_DETAILS;

-- Drop existing foreign key constraints
ALTER TABLE PRODUCT_STORE DROP FOREIGN KEY PRODUCT_STORE_ibfk_1;
ALTER TABLE PRODUCT_STORE DROP FOREIGN KEY PRODUCT_STORE_ibfk_2;

ALTER TABLE USER_FAVORITES DROP FOREIGN KEY USER_FAVORITES_ibfk_2;

ALTER TABLE `ORDER` DROP FOREIGN KEY ORDER_ibfk_2;
ALTER TABLE `ORDER` DROP FOREIGN KEY ORDER_ibfk_3;

ALTER TABLE REVIEW DROP FOREIGN KEY REVIEW_ibfk_2;
ALTER TABLE REVIEW DROP FOREIGN KEY REVIEW_ibfk_3;

-- Add constraints back with ON DELETE CASCADE
ALTER TABLE PRODUCT_STORE 
ADD CONSTRAINT PRODUCT_STORE_ibfk_1 
FOREIGN KEY (Product_ID) REFERENCES PRODUCT(Product_ID) ON DELETE CASCADE;

ALTER TABLE PRODUCT_STORE 
ADD CONSTRAINT PRODUCT_STORE_ibfk_2 
FOREIGN KEY (Store_ID) REFERENCES STORE(Store_ID) ON DELETE CASCADE;

ALTER TABLE USER_FAVORITES 
ADD CONSTRAINT USER_FAVORITES_ibfk_2 
FOREIGN KEY (Product_ID) REFERENCES PRODUCT(Product_ID) ON DELETE CASCADE;

ALTER TABLE `ORDER` 
ADD CONSTRAINT ORDER_ibfk_2 
FOREIGN KEY (Product_ID) REFERENCES PRODUCT(Product_ID) ON DELETE CASCADE;

ALTER TABLE `ORDER` 
ADD CONSTRAINT ORDER_ibfk_3 
FOREIGN KEY (Store_ID) REFERENCES STORE(Store_ID) ON DELETE CASCADE;

ALTER TABLE REVIEW 
ADD CONSTRAINT REVIEW_ibfk_2 
FOREIGN KEY (Product_ID) REFERENCES PRODUCT(Product_ID) ON DELETE CASCADE;

ALTER TABLE REVIEW 
ADD CONSTRAINT REVIEW_ibfk_3 
FOREIGN KEY (Store_ID) REFERENCES STORE(Store_ID) ON DELETE CASCADE;

-- Create missing product details tables with CASCADE
CREATE TABLE IF NOT EXISTS BOOK_DETAILS (
    Detail_ID INT PRIMARY KEY AUTO_INCREMENT,
    Product_ID INT NOT NULL,
    ISBN VARCHAR(13),
    Author VARCHAR(255),
    Publisher VARCHAR(255),
    Publication_Year INT,
    Pages INT,
    Language VARCHAR(50),
    Format VARCHAR(50), -- hardcover, paperback, etc.
    FOREIGN KEY (Product_ID) REFERENCES PRODUCT(Product_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ELECTRONICS_DETAILS (
    Detail_ID INT PRIMARY KEY AUTO_INCREMENT,
    Product_ID INT NOT NULL,
    Brand VARCHAR(255),
    Model VARCHAR(255),
    Warranty_Period VARCHAR(50),
    Technical_Specs TEXT,
    Power_Requirements VARCHAR(100),
    Connectivity VARCHAR(255),
    FOREIGN KEY (Product_ID) REFERENCES PRODUCT(Product_ID) ON DELETE CASCADE
);
